/*
 * LCD_private.h
 *
 *  Created on: Jul 4, 2023
 *      Author: User
 */

#ifndef INCLUDE_HAL_LCD_LCD_PRIVATE_H_
#define INCLUDE_HAL_LCD_LCD_PRIVATE_H_

#define FUNCTION_SET CONC_BIT(0 , 0 , 1 , LCD_DL , LCD_NO_OF_LINES , LCD_CHAR_FONT , 0 , 0)
#define DISPLAY_ON_OFF_CONTROL CONC_BIT(0,0,0,0,1,DISPLAY_SCREEN,DISPLAY_CURSOR,CURSOR_BLINK)
#define DISPLAY_CLEAR 0b00000001
#define ENTRY_MODE_SET CONC_BIT(0,0,0,0,0,1,DATA_DIRECTION,0)
#define LCD_ROW1_ADDDRESS 127
#define LCD_ROW2_ADDDRESS 191
#endif /* INCLUDE_HAL_LCD_LCD_PRIVATE_H_ */
