/*
 * External_INT_Privat.h
 *
 *  Created on: Jul 22, 2023
 *      Author: User
 */

#ifndef INCLUDE_MCAL_EXTERNAL_INTERRUPT_EXTERNAL_INT_PRIVAT_H_
#define INCLUDE_MCAL_EXTERNAL_INTERRUPT_EXTERNAL_INT_PRIVAT_H_

#define MCUCR_REG  (*(volatile u8*)0x55)
#define MCUCSR_REG (*(volatile u8*)0x54)
#define GICR_REG   (*(volatile u8*)0x5B)
#define GIFR_REG   (*(volatile u8*)0x5A)

//for MEXTI_voidConfig function
#define SENSE_MODE_MASK 3
#define EXTI0_SENSE_MODE_BITS 0
#define EXTI1_SENSE_MODE_BITS 2
#define EXTI2_SENSE_MODE_BITS 6

//FOR MEXTI_VOIDENABLE&&DISABLE FUNCTION
#define EXTI0_ENABLE_BIT 6
#define EXTI1_ENABLE_BIT 7
#define EXTI2_ENABLE_BIT 5

//FOR MEXTI_VOIDFLAG FUNCTION
#define EXTI0_FLAG_BIT 6
#define EXTI1_FLAG_BIT 7
#define EXTI2_FLAG_BIT 5

#endif /* INCLUDE_MCAL_EXTERNAL_INTERRUPT_EXTERNAL_INT_PRIVAT_H_ */
